name: ESLint Checks

on:
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: testdata
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run linter
        run: npm run pipeline-lint
