name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.json
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: false
