name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0 --legacy-peer-deps
          npm install @microsoft/eslint-formatter-sarif@2.1.7 --legacy-peer-deps

      - name: Run ESLint
        run: npx eslint .
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: false
